### ISSUE TITLE
Install/Configure user profiles

### ISSUE THREAD

**Issue by hexabinaer** [hexabinaer/cmsgarden#1]
- [x] Install module profile + patch (see below) @sanduhrs
- [x] Move current user fields to profiles @hexabinaer 

The legacy website has some fields attached to the user entity as well as profiles, such as 
* reference to cms terms, open source involvement, address, job
* not in full use but prepared: different profiles to display in the context of e. g. blog posts, lectures, user listings
* New in D8: fields with restricted access like association membership data

These user fields will be moved to profile entities.

We've been waiting for https://www.drupal.org/project/profile/issues/2899744 to be solved (multilanguage profiles). A tested patch is available.

**Comment by sanduhrs** [comment]
Install module profile + patch has been done.

**Comment by hexabinaer** [comment]
All profile types + fields created (and documented in spreadsheet).

To Do: 
* translate profile + field labels
* form layouts
* viewmodes (profiles + user)
* empty all current user fields (except username + password)
* deprecate/delete user fields

**Comment by hexabinaer** [comment]
all done
