### ISSUE TITLE
Find better solution for Add-buttons

### ISSUE THREAD

**Issue by hexabinaer** [hexabinaer/cmsgarden#14]
To avoid searching, we want to place "Add content" buttons in the context of where such content might be missing.

## Example 1

An event date (barcamp) has "session management" enabled. People can submit session proposals related to this event. We want a button near to the top of the proposals listing:

![grafik](https://user-images.githubusercontent.com/1636619/75578753-b77eee80-5a64-11ea-9093-80f4b927da15.png)

I placed tokenized markup in the header of the view that lists the sessions (this view is only rendered with active session management): `<a class="add-content button" href="/node/add/session?edit[field_event_relation][widget][0][target_id]={{ raw_arguments.nid }}">Add your session proposal!</a>`

This already works (using an autocomplete widget for the relation field). **But** the button not restricted to roles (that's okay, we can place a login field on the 403 page).

## Example 2

When viewing a node with basic information about a recurring event (event_defaults), there is a views block listing all upcoming dates related to this series. 
The pattern from above `(<a class="add-content button" href="/node/add/date?edit[field_date_node_ref][widget][0][target_id]={{ raw_arguments.field_date_node_ref_target_id }}">Add a date</a>)` does not work here, obviously because we're using an inline entity form as the widget for the reference field.

We might need more than these two examples. The concept is vital for the editor experience and should be extendable.

**Comment by hexabinaer** [comment]
Any ideas? Is there a module for this?

**Comment by sanduhrs** [comment]
Hm, perhaps this module: https://www.drupal.org/project/views_add_button ?

**Comment by hexabinaer** [comment]
Ha ha, who would have looked for _that_ name :-}

**Comment by sanduhrs** [comment]
Not sure it supports all the usecases, though.

**Comment by hexabinaer** [comment]
Good enough for what we need here.

We still have custom menus like (again) for the user welcome page.
