### ISSUE TITLE
Use variable fonts?

### ISSUE THREAD

**Issue by hexabinaer** [hexabinaer/cmsgarden#15]
I would love to use a (free) variable font (early adaption). 

Any objections? (apart from "great, as long as I don't have to deal with that")

**Comment by hexabinaer** [comment]
Example: https://www.axis-praxis.org/specimens/nobotoflex

In fact there are only 2-3 reasonable fonts available. The rest is either very restrictive with the licensing or too playful.

**Comment by sanduhrs** [comment]
Great, didn't know anything about variable fonts.
Here's a guide: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
