### ISSUE TITLE
Address field / address formatter contributions

### ISSUE THREAD

**Issue by hexabinaer** [hexabinaer/cmsgarden#43]
Address field formatter: https://www.drupal.org/project/issues/address_formatter
- [ ] Contribute fallback country format - currently there's no option to define a fallback format because a country has to be (single-)selected

Address field: https://www.drupal.org/project/issues/addressfield
- [ ] Contribute a "worldwide" country option?

**Comment by sanduhrs** [comment]
https://www.drupal.org/project/conditional_fields

**Comment by hexabinaer** [comment]
This is actually no task for an address field - we should have a boolean "online" field instead (form display can be managed with conditional fields (s. above).
