### ISSUE TITLE
Hide realname label (patch to test)

### ISSUE THREAD

**Issue by hexabinaer** [hexabinaer/cmsgarden#8]
Real name has a visible label by default (gosh, what an idea!)

![grafik](https://user-images.githubusercontent.com/1636619/75265683-8b0f6c00-57f1-11ea-9e65-877441aadcb7.png)

Some patch approaches later, it seems we have a working fix now:

https://www.drupal.org/project/realname/issues/3070681#comment-13437801

**Comment by sanduhrs** [comment]
Patch looks good, added to repo.

**Comment by hexabinaer** [comment]
Settings work.
