### ISSUE TITLE
Template overrides: hide title

### ISSUE THREAD

**Issue by hexabinaer** [hexabinaer/cmsgarden#9]
* Completely remove titles from all entity view modes except: 
  * full
  * teaser
* Replace all titles with field_title_html (if exists) in view modes "full" and "teaser"
* Preserve the link in teasers

Templates will later be moved to target theme folder (and maybe adjusted), see #10

**Comment by hexabinaer** [comment]
Review please ;-)

**Comment by sanduhrs** [comment]
Hint: if you put #9 in your commit message, it get's linked here.
If you then only comited the changes that are relevant for this issue, it makes it really easy for me to review.

**Comment by sanduhrs** [comment]
So, what I found is:
* in the node.html.twig we hide the label/title per default
* in the field--node--field-title-html.html.twig the html supporting title gets the markup we want
 
I did'nt find the template override for terms.
I didn't find the logic/config to display the html title only in full view mode.

**Comment by hexabinaer** [comment]
You are right. I am sorry :-/

What we want to achieve:
* Replace all titles with field_title_html (if exists)
* Completely remove titles from all entity view modes except: 
  * default
  * full
  * teaser

I'll change the issue description accordingly.

**Comment by hexabinaer** [comment]
I definitely messed it up:
> Twig\Error\LoaderError: Template "themes/cmsgtheme/templates/content/node.html.twig" is not defined. in Twig\Loader\ChainLoader->getCacheKey() (line 28 of /var/www/html/d8.cms-garden/web/core/themes/classy/templates/views/views-view-unformatted.html.twig).

**Comment by hexabinaer** [comment]
![Issue-illu_Template_overrides](https://user-images.githubusercontent.com/1636619/89557509-372e9780-d813-11ea-8661-e996f6d04dcb.png)

Hope this illustrates the problem: we are re-using bits and pieces of other content types quite often and we do not want the titles there.

**Comment by hexabinaer** [comment]
Current problem: with removing the titles I killed the teaser links ;-)

**Comment by hexabinaer** [comment]
Using a site-building solution now: manage_display

To Do: remove overriding templates
